addpath D:\grasp-master\grasp-master
addpath D:\MOSEK\mosek\10.0\toolbox\r2017a
addpath D:\yalmip\YALMIP-master\YALMIP-master
addpath D:\yalmip\YALMIP-master\YALMIP-master\extras
addpath D:\yalmip\YALMIP-master\YALMIP-master\solvers
addpath D:\yalmip\YALMIP-master\YALMIP-master\modules
addpath D:\yalmip\YALMIP-master\YALMIP-master\modules\parametric
addpath D:\yalmip\YALMIP-master\YALMIP-master\modules\moment
addpath D:\yalmip\YALMIP-master\YALMIP-master\modules\global
addpath D:\yalmip\YALMIP-master\YALMIP-master\modules\sos
addpath D:\yalmip\YALMIP-master\YALMIP-master\operators