clear

data = [];
dataCon = [];
y = load("ACC\VOI_acc_-12_36_20_1.mat");
data.y01 = y.xY.y;
dataCon = [dataCon,y.xY.y];
y = load("Fusiform_Gyrus\VOI_fg_32_-40_-22_1.mat");
data.y02 = y.xY.y;
dataCon = [dataCon,y.xY.y];
y = load("Insula_Lobe\VOI_il_34_20_10_1.mat");
data.y03 = y.xY.y;
dataCon = [dataCon,y.xY.y];
y = load("Middle_Frontal_Gyrus\VOI_mfg_-32_16_46_1.mat");
data.y04 = y.xY.y;
dataCon = [dataCon,y.xY.y];
y = load("Middle_Temporal_Gyrus\VOI_mtg_42_-54_10_1.mat");
data.y05 = y.xY.y;
dataCon = [dataCon,y.xY.y];
y = load("Opercularis\VOI_ifgop_50_14_30_1.mat");
data.y06 = y.xY.y;
dataCon = [dataCon,y.xY.y];
y = load("PCC\VOI_pcc_6_-40_24_1.mat");
data.y07 = y.xY.y;
dataCon = [dataCon,y.xY.y];
y = load("Posterior_Medial_Frontal\VOI_pmf_-4_8_58_1.mat");
data.y08 = y.xY.y;
dataCon = [dataCon,y.xY.y];
y = load("Superior_Frontal_Gyrus\VOI_sfg_22_56_6_1.mat");
data.y09 = y.xY.y;
dataCon = [dataCon,y.xY.y];
y = load("Superior_Medial_Gyrus\VOI_smg_16_58_-2_1.mat");
data.y10 = y.xY.y;
dataCon = [dataCon,y.xY.y];
y = load("Temporal_Pole\VOI_tp_44_20_-18_1.mat");
data.y11 = y.xY.y;
dataCon = [dataCon,y.xY.y];
y = load("Triangularis\VOI_ifgt_-50_20_10_1.mat");
data.y12 = y.xY.y;
dataCon = [dataCon,y.xY.y];
data.yCon = dataCon;

save("..\1603_data_voxel.mat","data");